package:
  name: genonets
  version: "2.0"

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

source:
  url: https://files.pythonhosted.org/packages/fb/ea/acf63ad7b54fc16ddacd0a9d1f4da4c455b5efe6fe7ec30b7eb2b0bd69e4/genonets-2.0.tar.gz
  sha256: c7f9605a48ab2796c273df232d377de56b9efe74d12831c384a358abb469242b

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-igraph >=0.7.1.post6
    - numpy >=1.8.2

test:
  imports:
    - genonets

about:
  home: https://github.com/fkhalid/genonets
  license: MIT License
  summary: 'Framework for creating and analyzing genotype networks from data.'
  license_family: MIT

extra:
  identifiers:
    - biotools:genonets
    - doi:10.1093/nar/gkw313
